# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fuzzyapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fuzzycontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_941672c537a14d08934c3897a12608a5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7cffc62f129f4059881bd283f4e7a25c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fuzzycontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_941672c537a14d08934c3897a12608a5 }}/brocoli:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fuzzyapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e76d8eea9b7c4c6fa744f971cb780c43 }}
        images: 'fuzzycontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_941672c537a14d08934c3897a12608a5 }}/brocoli:${{ github.sha }}'